#!/usr/bin/env python3
"""Generate the gallery from standalone Markdown diagrams; --check never writes.

This documentation helper checks synchronization, not Mermaid syntax or layout.
It uses only the Python standard library and does not execute diagram contents.
"""

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DIAGRAM_DIR = PROJECT_ROOT / "docs" / "diagrams"
DIAGRAMS = (
    ("development-flow", "项目开发流程"),
    ("system-architecture", "Agent 系统架构"),
    ("agent-runtime", "Agent 运行与验证反馈"),
    ("dependency-graph", "项目任务依赖"),
    ("learning-path", "Agent Engineering 学习路径"),
)


def diagram_text(path):
    document = path.read_text(encoding="utf-8")
    openings = re.findall(r"^```mermaid[ \t]*$", document, re.MULTILINE)
    blocks = re.findall(
        r"^```mermaid[ \t]*\n(.*?)^```[ \t]*$",
        document,
        re.MULTILINE | re.DOTALL,
    )
    if len(openings) != 1 or len(blocks) != 1 or not blocks[0].strip():
        raise ValueError(f"Expected one non-empty fenced mermaid block: {path.name}")
    return blocks[0].strip()


def gallery_text():
    parts = [
        "<!-- Generated by scripts/sync_diagrams.py; edit the five diagram .md files instead. -->",
        "# Mermaid 图展示",
        "本页从五个独立 Markdown 图源中的 `mermaid` 代码块生成。"
        "图描述目标设计，不代表所有模块已实现。",
        "在 VS Code 中打开本页或下方任意独立图源，按 `⌘⇧V` 打开 Markdown 预览；"
        "也可在命令面板选择 `Markdown: Open Preview to the Side`。"
        "此格式符合 [Markdown Preview Mermaid Support 的用法]"
        "(https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)。",
        "编辑图源后，在项目根运行 `python3 scripts/sync_diagrams.py`；"
        "用 `python3 scripts/sync_diagrams.py --check` 检查是否同步。"
        "同步检查不代替 Mermaid 解析或渲染检查。",
        "产品范围见 [product.md](../product.md)，实际状态见 "
        "[当前能力与验证范围](../status.md)。",
    ]
    for stem, title in DIAGRAMS:
        source = diagram_text(DIAGRAM_DIR / f"{stem}.md")
        parts.extend(
            [
                f"## {stem}",
                f"{title}。独立预览与编辑：[{stem}.md]({stem}.md)。",
                f"```mermaid\n{source}\n```",
            ]
        )
    return "\n\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing")
    args = parser.parse_args()
    destination = DIAGRAM_DIR / "README.md"
    try:
        expected = gallery_text()
        if args.check:
            actual = (
                destination.read_text(encoding="utf-8")
                if destination.exists()
                else None
            )
            if actual != expected:
                print(
                    "OUT OF SYNC: run python3 scripts/sync_diagrams.py", file=sys.stderr
                )
                return 1
            print("PASS: Mermaid gallery matches all 5 source files.")
            return 0
        destination.write_text(expected, encoding="utf-8")
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    print("Updated docs/diagrams/README.md from 5 Mermaid source files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
